import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";

import { AuthModalProvider } from "@/components/auth/auth-modal-provider";
import { AuthSessionProvider } from "@/components/auth-session-provider";
import { CartProvider } from "@/components/CartProvider";

import "./globals.css";

const googleOAuthConfigured =
  Boolean(process.env.AUTH_GOOGLE_ID?.trim()) &&
  Boolean(process.env.AUTH_GOOGLE_SECRET?.trim());

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: "#fdf2f5",
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col text-black">
        <AuthSessionProvider>
          <AuthModalProvider googleOAuthConfigured={googleOAuthConfigured}>
            <CartProvider>{children}</CartProvider>
          </AuthModalProvider>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
